version: '3'
services:
  redis:
    image: redis
    command: redis-server
    volumes:
    - /home/ubuntu/redis:/data
    ports:
    - "6379:6379"
    restart: always

  app:
    restart: always
    build: .
    command: >
      bash -c
      "gunicorn  Qinghuiyue.wsgi:application -c gunicorn.conf"
    ports:
      - "8000"
    volumes:
    - /home/ubuntu/static:/code/static
    environment:
      - TZ=Asia/Shanghai
    networks:
      - backend
      - database
    depends_on:
      - db
      - redis

  db:
    image: mongo
    volumes:
    - /home/ubuntu/mongodb/data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=thuC0
      - MONGO_INITDB_ROOT_PASSWORD=C0Qinghuiyue
      - TZ=ASIA/SHANGHAI
    networks:
      - database
    ports:
    - "27017:27017"
  nginx:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile_nginx
    ports:
    - "8000:8000"
    depends_on:
      - app
    volumes:
    - ./config/nginx:/etc/nginx/conf.d
    - /home/ubuntu/static:/static
    networks:
      - backend
networks:
  backend:
    driver: bridge
  database:
    driver: bridge
