version: '3'
services:
  app:
    restart: always
    build: .
    command: >
      bash -c
      "python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    environment:
      - TZ=Asia/Shanghai